[package]
name = "extract_anchors"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1.0.61" }
tracing = { version = "0.1.40" }
walkdir = { version = "2" }
tracing-subscriber = { version = "0.3.18" }
